version: "3.9"
services:
  analyzer:
    build:
      context: .
    container_name: analyze-code
    tty: true
    volumes:
      - type: bind
        source: .
        target: /work
      - type: volume
        source: packages
        target: /usr/local/lib/python3.12/site-packages

volumes:
  packages: